### PR TITLE
WIP: extend Particle constructor

### PR DESCRIPTION
**Pull request by simeonschaub**
Still need to add tests and probably some docs as well. What do you think about this approach, @mmikhasenko?

### CODE REVIEW

**Comment by mmikhasenko** [comment]
Nice, it makes the constructor much more flexible.
There is an `intersect` function in `Base`. It looks to me that it can simplify the `get_anyof` function.

**Comment by mmikhasenko** [comment]
I do not understand `@generated`

**Comment by mmikhasenko** [comment]
(ups, closed by mistake)

**Comment by simeonschaub** [comment]
> There is an intersect function in Base. It looks to me that it can simplify the `get_anyof` function.

The problem is that it's critical that constant propagation can figure out what type `get_anyof` will return at compile time, because otherwise `to_xyzt` won't be type stable. I did try multiple approaches without `@generated`, but none of them ended up being type stable. Eventually, the compiler may improve, so this is type stable even without having to resort to `@generated`.
In case you are confused about `@generated`, the manual has a section where they are explained a bit: https://docs.julialang.org/en/v1/manual/metaprogramming/#Generated-functions. They basically let us move calculations in the type domain to compile time instead of runtime.

**Comment by mmikhasenko** [comment]
Closing for now. There are cool ideas how to dispatch on names of arguments here, so might come back at some point, or Julia get it implemented.

btw, @simeonschaub 
we started to work with JuliaHEP crowd on common interface [here](https://github.com/JuliaHEP/LorentzVectorBase.jl)

**Comment by mmikhasenko** [comment]
Follow-up note (May 2026, Julia 1.11): re-checked whether we can drop `@generated` for the flexible keyword constructor — still no. `Base.intersect`-style lookup remains type-unstable; the `@generated get_anyof` approach from this PR is still the practical one if we revive name-based construction.

Since this was closed, the package moved to a single immutable `FourVector` with the [LorentzVectorBase.jl](https://github.com/JuliaHEP/LorentzVectorBase.jl) interface, which partly addresses cross-package compatibility on the accessor side (without the flexible ctor ideas here).

Related: [#19](https://github.com/mmikhasenko/FourVectors.jl/pull/19) adds cylindrical coordinates (`FourVectorCyl`, pt/η/φ) as a separate type — overlapping with the `pt/eta/phi` construction path sketched in this PR, but as a first-class LorentzVectorBase type rather than ctor dispatch.

We might still return to mutable four-vectors for hot loops; see [#20](https://github.com/mmikhasenko/FourVectors.jl/issues/20) for a benchmark proposal before deciding.

**Pull request closed without merging**
